Repository Dean6622/Comp4350-Team3, pull requests merged in 2025-03, with the labels that each got.

#109 Issue 020 set up reminder
  server/src/app.ts
  server/src/controller/reminderController.ts
  server/src/db/reminderDB.ts
  server/src/db/reminderService.ts
  server/src/middleware/dbValidation.ts
  server/src/routes/reminder.ts
Labels: dev task

#139 fixed goal bug
  frontend/components/ui/GoalEditModal.tsx
Labels: bug

#138 Add unit tests for Sprint3
  server/package-lock.json
  server/package.json
  server/src/controller/reminderController.ts
  server/src/db/reminderService.ts
  server/src/tests/controller/goalsController.test.ts
  server/src/tests/controller/loginController.test.ts
  server/src/tests/controller/reminderController.test.ts
  server/src/tests/controller/tagController.test.ts
  server/src/tests/controller/transactionController.test.ts
  server/src/tests/controller/userController.test.ts
  server/src/tests/db/goalsService.test.ts
  server/src/tests/db/reminderService.test.ts
  server/src/tests/db/tagService.test.ts
  server/src/tests/db/transactionService.test.ts
  server/src/tests/db/userService.test.ts
Labels: Development, test

#143 Add sonar-build.yml for security scanner
  .github/workflows/sonar-build.yml
  sonar-project.properties
Labels: Infrastructure, High
