Repository Dean6622/Comp4350-Team3, pull requests merged in 2025-02, with the labels that each got.

#54 Create basic structure for server routing layer
  server/eslint.config.mjs
  server/package.json
  server/src/app.ts
  server/src/public/stylesheets/main.css
  server/src/routes/index.ts
  server/src/routes/profile.ts
  server/src/routes/user.ts
  server/src/views/error.pug
  server/src/views/index.pug
  server/src/views/layout.pug
  server/tsconfig.json
Labels: Development, High

#58 Create the structure of middleware layer
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/middleware/errorHandler.ts
  server/src/middleware/loggers.ts
  server/src/routes/index.ts
Labels: Development, High

#67 Create control layer
  server/src/controller/indexController.ts
  server/src/controller/profileController.ts
  server/src/routes/index.ts
  server/src/routes/profile.ts
Labels: High

#70 Modify server setting so that it allows requests from frontend
  frontend/app/api/auth.ts
  frontend/app/auth/reset-password/page.tsx
  frontend/app/auth/signup/page.tsx
  frontend/components/ui/Input.tsx
  frontend/lib/utils.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/loginController.ts
  server/src/routes/login.ts
Labels: bug

#78 Create transaction list
  frontend/app/transactions/page.tsx
  frontend/components/ui/TransactionList.tsx
Labels: dev task

#91 Build unit tests for user stories in spr2
  package.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/loginController.ts
  server/src/controller/tagController.ts
  server/src/controller/transactionController.ts
  server/src/controller/userController.ts
  server/src/db/tagService.ts
  server/src/db/transactionService.ts
  server/src/db/userService.ts
  server/src/middleware/authenticator.ts
  server/src/routes/index.ts
  server/src/routes/login.ts
  server/src/routes/transaction.ts
  server/src/routes/user.ts
  server/tests/controller/indexController.test.ts
  server/tests/controller/loginController.test.ts
  server/tests/controller/tagController.test.ts
  server/tests/controller/transactionController.test.ts
  server/tests/controller/userController.test.ts
  server/tsconfig.json
Labels: Development, High
